### PR TITLE
Merge official repo

### PR DESCRIPTION
**Pull request by KylinMountain**
## Description

[Provide a brief description of the changes made in this pull request.]

## Related Issues

[Reference any related issues or tasks that this pull request addresses.]

## Proposed Changes

[List the specific changes made in this pull request.]

## Checklist

- [ ] I have tested these changes locally.
- [ ] I have reviewed the code changes.
- [ ] I have updated the documentation (if necessary).
- [ ] I have added appropriate unit tests (if applicable).

## Additional Notes

[Add any additional notes or context that may be helpful for the reviewer(s).]

### CODE REVIEW

**Comment by KylinMountain** [comment]
Can not query, there's bug...

**Comment by KylinMountain** [comment]
如何在本地切换分支然后合并来自microsoft的更新

```
# 添加 upstream 远程仓库（如果尚未添加）
git remote add upstream https://github.com/microsoft/repository-name.git

# 获取最新的远程仓库信息
git fetch origin
git fetch upstream

# 切换到您的 PR 分支
git checkout cutomize

# 创建一个新的本地分支
git checkout -b cutomize-update

# 选择性地合并或挑选更改
git cherry-pick <commit-hash>  # 替换 <commit-hash> 为您想要的特定提交的哈希值

# 处理完成后推送到您的 fork（如果需要）
git push origin cutomize-update
```

**Comment by meltingrock** [comment]
> 如何在本地切换分支然后合并来自microsoft的更新
> 
> ```
> # 添加 upstream 远程仓库（如果尚未添加）
> git remote add upstream https://github.com/microsoft/repository-name.git
> 
> # 获取最新的远程仓库信息
> git fetch origin
> git fetch upstream
> 
> # 切换到您的 PR 分支
> git checkout cutomize
> 
> # 创建一个新的本地分支
> git checkout -b cutomize-update
> 
> # 选择性地合并或挑选更改
> git cherry-pick <commit-hash>  # 替换 <commit-hash> 为您想要的特定提交的哈希值
> 
> # 处理完成后推送到您的 fork（如果需要）
> git push origin cutomize-update
> ```

Hi and Thank you, which commit hashes are you comfortable to include?

**Comment by KylinMountain** [comment]
> > 如何在本地切换分支然后合并来自microsoft的更新
> > ```
> > # 添加 upstream 远程仓库（如果尚未添加）
> > git remote add upstream https://github.com/microsoft/repository-name.git
> > 
> > # 获取最新的远程仓库信息
> > git fetch origin
> > git fetch upstream
> > 
> > # 切换到您的 PR 分支
> > git checkout cutomize
> > 
> > # 创建一个新的本地分支
> > git checkout -b cutomize-update
> > 
> > # 选择性地合并或挑选更改
> > git cherry-pick <commit-hash>  # 替换 <commit-hash> 为您想要的特定提交的哈希值
> > 
> > # 处理完成后推送到您的 fork（如果需要）
> > git push origin cutomize-update
> > ```
> 
> Hi and Thank you, which commit hashes are you comfortable to include?

only this two commit I have merged.
image

**Pull request merged**
